image: continuumio/miniconda3

before_script:
  - conda update -c conda-forge --all -y
  - pip install -r requirements.txt
  - pip install python-dotenv

test:
    script:
     - python3 -m unittest discover
