image: continuumio/miniconda3

services:
    - rroemhild/test-openldap:latest
    - redis:latest

test:
  tags:
    - docker
  before_script:
    - conda init bash
    - source /root/.bashrc
    - conda update -c conda-forge --all -y
    - pip install -r requirements.txt
  script:
     - python3 -m unittest tests/test_hancock.py