image: continuum/miniconda3

before_script:
  - conda update -c conda-forge --all -y
  - pip install -r requirements.txt

job:
  services:
    - rroemhild/test-openldap:latest
    - redis:latest

test:
    script:
     - python3 -m unittest discover
