image: continuumio/miniconda3

services:
    - rroemhild/test-openldap:latest
    - redis:latest

test:
  tags:
    - docker
  before_script:
    - apt-get update
    - apt install build-essential --all -y
    - conda update -c conda-forge --all -y
    - pip install -r requirements.txt
  script:
     - python3 -m unittest discover
