image: continuumio/miniconda3

services:
    - rroemhild/test-openldap:latest
    - redis:latest

test:
  tags:
    - docker
  before_script:
    - sudo apt install build-essentials
    - conda update -c conda-forge --all -y
    - pip install -r requirements.txt
  script:
     - python3 -m unittest discover
