version: '3'
services:
    redis:
        image: redis
    flask:
        image: webapp-flask
        build:
            context: .
            dockerfile: Dockerfile
        command:
            - uwsgi
            - --ini
            - app.ini
            - --http-socket
            - 0.0.0.0:5000
        depends_on:
            - redis
        environment:
            FLASK_ENV: development
            HANCOCK_REDIS_HOSTNAME: redis
        env_file:
            # create this file yourself!
            - .env
        ports:
            - "5000:5000"
    worker:
        build:
            context: .
            dockerfile: ConsumerDockerfile
        volumes:
            - ./worker:/app
        environment:
            - PYTHONUNBUFFERED=1


