name: hancock
channels:
  - conda-forge
dependencies:
  -  python=3.8
  - boto3
  - botocore
  - flask
  - flask-jwt-extended
  - flask-ldap3-login
  - flask-restx
  - python-dotenv
  - redis
  - uwsgi