name: hancock
channels:
  - conda-forge
dependencies:
  - python=3.8
  - boto3
  - botocore
  - flask
  - flask-jwt-extended
  - flask-login
  - flask-restx
  - python-dotenv
  - redis-py
  - nose2
  - uwsgi
  - mockredispy
  - requests
  - pika
  - logging-helpers
  - werkzeug